### ISSUE TITLE
Revdep issue with vctrs

### ISSUE THREAD

**Issue by lionel-** [r-prof/winch#53]
Is this ran on CRAN machines?

```r
  Loading required package: vctrs
  Error in winch::winch_init_library(vctrs:::vctrs_init$dll[["path"]]) : 
    object 'vctrs_init' not found
```

**Comment by krlmlr** [comment]
It's fixed in the devel version, for a CRAN release I'll need to get rid of the warning at https://cran.r-project.org/web/checks/check_results_winch.html. Does that ring a bell?

**Comment by krlmlr** [comment]
```
trace_back_backtrace.c: In function 'cb_get_name_ip':
trace_back_backtrace.c:87:19: warning: unknown conversion type character 'l' in format [-Wformat=]
   87 |   sprintf(ip_buf, "%.16" PRIxPTR, pc);
      |                   ^~~~~~
In file included from trace_back_backtrace.c:8:
d:\rtools42\x86_64-w64-mingw32.static.posix\include\inttypes.h:37:18: note: format string is defined here
   37 | #define PRIx64 "llx"
      |                  ^
trace_back_backtrace.c:87:19: warning: too many arguments for format [-Wformat-extra-args]
   87 |   sprintf(ip_buf, "%.16" PRIxPTR, pc);
      |                   ^~~~~~
```

**Comment by krlmlr** [comment]
FWIW, I worked around in https://github.com/r-prof/winch/commit/b450b7e89bc13562cace5ce36048b31f74631ba6. This issue is a real mess.

**Comment by krlmlr** [comment]
Fixed on CRAN now.

**Comment by lionel-** [comment]
This looks like the issue of Microsoft's clib not conforming to the C standard. The mingw toolchain reproduces the Microsoft behaviour. You can set a variable to use the gcc version instead. But even then you might still get false positive warnings about it in some cases.

See https://github.com/r-lib/rlang/blob/22fe9e9d729d562fcfd580c7a350f56d7a864639/src/rlang/rlang.h#L4-L21
